# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-08 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('state', '0002_auto_20181004_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllFramework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AllLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='state.State')),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_1', models.IntegerField(null=True)),
                ('frame_2', models.IntegerField(null=True)),
                ('frame_3', models.IntegerField(null=True)),
                ('frame_4', models.IntegerField(null=True)),
                ('frame_5', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('all_frameworks', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frameworks', to='devs.AllFramework')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dev_frame', to='devs.Developer')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_1', models.IntegerField(null=True)),
                ('lang_2', models.IntegerField(null=True)),
                ('lang_3', models.IntegerField(null=True)),
                ('lang_4', models.IntegerField(null=True)),
                ('lang_5', models.IntegerField(null=True)),
                ('short_bio', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('all_languages', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='devs.AllLanguage')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dev_lang', to='devs.Developer')),
            ],
        ),
    ]
