# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-07 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='lang_1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='lang_2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='lang_3',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='lang_4',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='lang_5',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='short_bio',
            field=models.TextField(max_length=500),
        ),
    ]
