# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-05 07:09
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='developer',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
