# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-07 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0002_auto_20181007_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='short_bio',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
